version: '3'

services:
  openai-whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      ASR_ENGINE: faster_whisper
      ASR_MODEL: large-v2
    ports:
      - 9000:9000
